- command/download.go
- nerd/aws/data_client.go
Adds a check to the `nerd download` command to see if files already exist on disk. If so the user is asked wether to overwrite or skip. The `--always-overwrite` flag could be set to prevent from asking for user input.
> Add file overwrite checking mechanism

- command/utils.go
- command/worker_start.go
- nerd/client/auth/v1/client.go
- nerd/client/auth/v1/ops_client.go
- nerd/client/auth/v1/payload/jwt.go
- nerd/client/auth/v1/token_client.go
- nerd/jwt/authapi_provider.go
- nerd/jwt/config_provider.go
- nerd/jwt/config_provider_test.go
- nerd/jwt/env_provider.go
- nerd/jwt/jwt.go
- nerd/jwt/provider.go
- nerd/jwt/test_utils.go
- nerd/oauth/config_provider.go
- nerd/oauth/config_provider_test.go
- nerd/utils/test_utils.go
- jwt EnvProvider and jwt ConfigProvider now try to refresh a JWT if it's expired and a refresh token is present
- it's now possible to fetch a JWT+RefreshToken from the Auth server to pass to a worker in universe.
> JWT Refresh logic

- command/dataset.go
- command/project_expel.go
- command/project_place.go
- command/worker_list.go
- command/worker_start.go
- command/worker_stop.go
- main.go
- nerd/client/batch/v1/payload/placement.go
- nerd/client/batch/v1/payload/worker.go
- nerd/client/batch/v1/placement.go
- nerd/client/batch/v1/worker.go
> Project placement and worker start,list,stop

- command/dataset_upload.go
This allows for for easier selection and copy/pasting of the dataset id. Besides, quotes seem not be used around other outputted ids.
> Remove quotes from output of datasetID

- cmd/dataset_list.go
- cmd/job_list.go
- cmd/job_run.go
- crd/pkg/apis/stable.nerdalize.com/v1/types.go
- crd/pkg/client/clientset/versioned/fake/clientset_generated.go
- crd/pkg/client/clientset/versioned/fake/register.go
- crd/pkg/client/clientset/versioned/scheme/register.go
- svc/kube_delete_dataset_test.go
- svc/kube_fetch_job_logs_test.go
- svc/kube_get_dataset.go
- svc/kube_get_dataset_test.go
- svc/kube_list_datasets.go
- svc/kube_list_datasets_test.go
- svc/kube_list_jobs.go
- svc/kube_list_jobs_test.go
- svc/kube_update_dataset.go
- svc/kube_update_dataset_test.go
Closes #243, closes #244 
This pull request adds a new set of information:
> Inform users about datasets usage (for/from which job a dataset is used)

- cmd/flex/main.go
- pkg/transfer/s3uploader.go
- pkg/transfer/transfer.go
The size in the custom resource is now updated when an output is uploaded to S3.
> Update dataset size when uploading output

- cmd/flex/main.go
- cmd/job_run.go
- cmd/job_run_test.go
- cmd/opts.go
- make.sh
- svc/kube_run_job.go
- svc/kube_run_job_test.go
- svc/kube_update_dataset_test.go
- svc/svc.go
- svc/utils_test.go
The commandline syntax for inputs uses the `<JOB_DIR>:[DATASET_NAME]` syntax, but Windows paths usually have a colon in them, like `C:\something`. This currently makes it nigh impossible to use `nerd` on Windows.
Issues:
Format can be fixed by adding `forceposix` build tag for the `go-flags` package:
https://github.com/jessevdk/go-flags/blob/4cc2832a6e6d1d3b815e2b9d544b2a4dfb3ce8fa/optstyle_windows.go
Update: Closes #159 
Closes #283
> Fix various CLI problems including Windows fixes

- cmd/job_list.go
- cmd/job_run.go
- crd/pkg/client/clientset/versioned/fake/clientset_generated.go
- crd/pkg/client/clientset/versioned/fake/register.go
- crd/pkg/client/clientset/versioned/scheme/register.go
- svc/kube_list_jobs.go
- svc/kube_list_jobs_test.go
- svc/kube_run_job.go
- svc/kube_run_job_test.go
This pull request introduces two new options for the `nerd job run` command: `--memory` and `--vcpu`. It will let the users specify how much resources they want to spend on one job.
It's good to know that for the memory, lowercase units do not work: [https://github.com/kubernetes/kubernetes/issues/49442](https://github.com/kubernetes/kubernetes/issues/49442), and allowed units can be found [here](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory).
> Resource requests for jobs

- cmd/flex/main.go
For now we chose to limit the write space to 2Gbs. This will later evolve using user data (dataset limits, storage limits when this will be implemented). Closes #290
> Update flex volume write space value

- cmd/cmd.go
- cmd/dataset_upload.go
- cmd/job_run.go
- crd/pkg/client/clientset/versioned/fake/clientset_generated.go
- crd/pkg/client/clientset/versioned/fake/register.go
- crd/pkg/client/clientset/versioned/scheme/register.go
- pkg/transfer/archiver/tar_archiver.go
- pkg/transfer/archiver/types.go
- pkg/transfer/types.go
This pull request fixes #263 (partly) thanks to @advanderveer 's help. 
It also remove datasets that were created by the `nerd job run` command if this command fails (fixes #263). Same, when `nerd dataset upload` fails to send data to S3, it will delete the dataset from k8s (fixes #302).
> Dataset handling enhancement

- cmd/dataset_download.go
This pull request updates the way we handle directories for `nerd dataset download` when the options `--input-of` or `--output-of` are used. Before, one subdirectory was created for each dataset even when there was only one dataset which was quite confusing.
> Update directory tree for dataset download

- cmd/errors.go
- cmd/job_list.go
Resolves #321 and resolves #361
> Update hints 

- cmd/cmd.go
- cmd/dataset.go
- cmd/dataset_delete.go
- cmd/dataset_download.go
- cmd/dataset_list.go
- cmd/dataset_upload.go
- cmd/job.go
- cmd/job_delete.go
- cmd/job_list.go
- cmd/job_logs.go
- cmd/job_run.go
Closes #354 
`--kube-config` and `--timeout` are now part of the global options. And when we create a command, we can now provide some additional options that will appear under the `Advanced options` section
> Create advanced and global options

- cmd/dataset_upload.go
- cmd/opts.go
- pkg/transfer/store/s3_store.go
- spec.json
This pull requets adds the ability to configure private s3 buckets whenever a dataset is uploaded from Nerd.
> Make it possible to configure private S3 buckets

- cmd/job_run.go
- pkg/kubevisor/visor.go
- spec.json
- svc/kube_create_secret.go
- svc/kube_create_secret_test.go
- svc/kube_delete_dataset_test.go
- svc/kube_delete_secret.go
- svc/kube_delete_secret_test.go
- svc/kube_get_dataset.go
- svc/kube_get_secret.go
- svc/kube_get_secret_test.go
- svc/kube_list_secret.go
- svc/kube_list_secrets_test.go
- svc/kube_run_job.go
- svc/kube_update_dataset.go
- svc/kube_update_secret.go
- svc/kube_update_secret_test.go
This pull request will close #378.
Edge case:
If users make a typo in their username/password and the cli automatically reuse a secret, users won't be able to modify their secret which will lead jobs to fail. This is why people can use the `--clean-creds` flag with the `nerd job run` command to be asked again for their credentials.
> Add option to use private images

- examples/quota/q1.yml
- pkg/transfer/archiver/opts.go
- pkg/transfer/archiver/tar_archiver.go
- pkg/transfer/kube_manager.go
This pull request allows users to upload more than 1Gb as their output dataset.
The flexvolume should be rebuilt and redeployed for this pull request to be properly tested.
After this pull request is merged, a new flex volume daemonset should be deployed.
> Update SizeLimit option for archiver

- cmd/cluster_list.go
- cmd/cluster_set_default.go
- cmd/login.go
- cmd/opts.go
- pkg/kubeconfig/kubeconfig.go
- pkg/populator/generic.go
- pkg/populator/populator.go
- pkg/populator/types.go
It is now possible to set a default cluster using its name or its identifier:
This was done :
- to help people to set a default cluster if a name is too complex
- to avoid weird situation where a cluster doesn't have a name
> Fix set-default command and remove useless populator client

- cmd/flex/main.go
- pkg/transfer/archiver/tar_archiver.go
This pull request should mitigate the issue #407:
- before, if there was an error during the unmount, it was trying to delete as much as possible, but the overlayFS was still mounted.
- during the archiving process, the directory was opened but never closed. This could cause the unmount to fail as the resources were marked as busy.
> update error handling logic for flexvolume unmount

- cmd/job_run.go
This pull request sets new default values for memory and vcpu requests when users start a job with `nerd job run`. The new values let users run their application on a private cluster even with the smallest node possible without thinking about the resource requests.
> Update default resource request values

- cmd/login.go
In case the browser fails to open properly users can always refer to the URL printed on the commandline.
> Change login command to always display login URL
