nerdalize/nerd

command/download.go, command/upload.go, command/utils.go, nerd/data/data.go, nerd/user.go
This feature adds data upload / download functionality to the CLI.
To run, export the following AWS environment variables:
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
=> Feature data upload / download

command/utils.go, command/utils_test.go, nerd/client/nerdapi.go, nerd/client/nerdapi_test.go
Just a bit of extra code to test the client
=> Add doRequest test

nerd/payload/dataset.go, nerd/payload/task.go, nerd/payload/worker.go
finish up payloads for current universe version
=> Feature project scoped payloads

nerd/client/credentials/nerd_token.go, nerd/client/nerdapi.go
Allow project id to be configurable for API endpoint construction
=> Add projects prefix to URL

command/utils.go, nerd/client/nerdapi.go, nerd/conf/conf.go, nerd/user.go
Move the project ID to the config file.
=> Move project ID to config

command/opts.go, command/utils.go, nerd/aws/data_client.go, nerd/aws/provider.go, nerd/client/authapi.go, nerd/client/credentials/credentials.go, nerd/client/credentials/nerd_token.go, nerd/client/credentials/provider/authapi.go, nerd/client/credentials/provider/chain.go, nerd/client/credentials/provider/config.go, nerd/client/credentials/provider/env.go, nerd/client/credentials/provider/env_test.go, nerd/client/credentials/provider/provider.go, nerd/client/nerdapi.go, nerd/client/nerdapi_test.go, nerd/conf/conf.go, nerd/conf/conf_test.go
=> Add comments

command/login.go, command/utils.go
`nerd login` can be used either with the `--user` and `--pass` flags, or by asking input on stdin.
=> Add login command functionality

README.md, examples/docker-base-image/Dockerfile, examples/docker-base-image/README.md, examples/docker-base-image/entrypoint.sh
This PR adds an example that shows how to use the nerd container as a base container.
=> Add container example

command/download.go
Create output folder if it doesn't exist yet for `nerd download`.
=> Create output folder if it doesn't exist yet

nerd/client/error.go, nerd/payload/error.go
Add more user friendly message description when 404 is received from the API.
=> Add 404 message description

command/command.go, command/download.go, command/login.go, command/logs.go, command/opts.go, command/run.go, command/status.go, command/upload.go, command/work.go, main.go
Help messages now look nice and are up-to-date.
=> Show help messages

command/dataset_download.go, command/dataset_upload.go, nerd/aws/data_client.go, nerd/client/batch/v1/dataset.go, nerd/client/batch/v1/payload/dataset.go, nerd/client/data/v1/chunked.go, nerd/jwt/env_provider_test.go, nerd/jwt/jwt.go, nerd/jwt/provider.go
- Adds heartbeat mechanism to upload command
- Adds wait-for-upload mechanism to download command
=> Dataset upload status

command/dataset_download.go, command/dataset_list.go, command/dataset_upload.go, command/project_expel.go, command/project_list.go, command/project_place.go, command/task_describe.go, command/task_failure.go, command/task_heartbeat.go, command/task_list.go, command/task_receive.go, command/task_start.go, command/task_stop.go, command/task_success.go, command/worker_logs.go, command/workload_describe.go, command/workload_download.go, command/workload_list.go, command/workload_start.go, command/workload_stop.go, command/workload_work.go, nerd/conf/session.go
=> no longer allow running commands without setting a project first

nerd/client/batch/v1/billing_package.go, nerd/client/batch/v1/client.go, nerd/client/batch/v1/payload/billing_package.go
Updated payloads to match with universe billing package controller
=> Fix quota payloads

nerd/conf/conf.go
Can be released after nerdalize/authentication/pull/138 is deployed (expected Fri, Sept 1st)
It makes the login experience better.
=> changed url where client goes after login successfull

nerd/service/datatransfer/v1/tar.go, nerd/service/datatransfer/v1/tar_test.go
=> added path normalization on tar+untar

README.md, nerd.svg
We want to make sure users that arrive on the README can easily move to other sources of inspiration
=> Added a bit more marketing

cmd/cmd.go, cmd/errors.go, cmd/job.go, cmd/job_delete.go, cmd/job_logs.go, cmd/job_run.go, command/login.go, command/project_expel.go, command/project_place.go, command/project_set.go, nerd/client/auth/v1/client.go, nerd/client/auth/v1/ops_client.go, nerd/client/auth/v1/token_client.go, nerd/client/batch/v1/client.go, nerd/client/batch/v1/jwt_provider.go, nerd/jwt/authapi_provider.go, nerd/service/working/v1/working.go, nerd/version.go
=> Revert "Feedback improvement"

crd/pkg/apis/stable.nerdalize.com/v1/types.go, pkg/kubevisor/visor.go, svc/kube_get_dataset.go, svc/kube_update_dataset.go, svc/kube_update_dataset_test.go
+ tests and UpdateDataset to svc package
=> Add update resource method to visor

.gitignore, cmd/dataset_upload.go, glide.lock, installers/msi/Product.wxs, installers/msi/make.sh, installers/msi/nerd.wixproject
Create a .msi installer that sets up the Nerd CLI on a users computer
=> Windows Installer

cmd/dataset_list.go, cmd/job_list.go
=> fix output message for resource listing

cmd/dataset_download.go
=> add possibility to download datasets by providing job identifier

cmd/job_list.go, svc/kube_list_jobs.go, svc/kube_list_jobs_test.go
=> support list of inputs and ouputs for nerd job list

cmd/cmd.go, cmd/dataset_upload.go, cmd/job_run.go, pkg/transfer/archiver/tar_archiver.go
This pull requests closes #305 and closes #329
=> Return error if trying to upload non existing or empty dir

cmd/cmd.go, cmd/dataset_upload.go, cmd/job_run.go, pkg/transfer/archiver/tar_archiver.go
=> remove datasets on a failed nerd job run if they are ad-hoc ones

cmd/dataset_delete.go, cmd/job_delete.go
This is a first step to close #333 and to resolve #314
=> Provide a way to delete multiple datasets and jobs at the same time

cmd/cmd.go, cmd/errors.go, cmd/opts.go, command/login.go, command/project_set.go
* Fixes #312 and #313 by removing "project" from the cli output and by providing better feedback
* Fixes #325 by removing config from kube config file if there is a problem when we set a project/cluster
=> Remove project naming

cmd/job_list.go, examples/quota/q1.yml, glide.lock, glide.yaml, pkg/kubevisor/visor.go, svc/kube_fetch_job_logs.go, svc/kube_list_datasets.go, svc/kube_list_jobs.go, svc/kube_list_jobs_test.go, svc/kube_list_quotas.go
fixes #317 partially, opens up fixing #341 and #342
=> Provide better feedback about resource usage and pod waiting

cmd/dataset_download.go, cmd/dataset_upload.go, cmd/errors.go, cmd/job_run.go, pkg/transfer/archiver/tar_archiver.go, pkg/transfer/archiver/tar_archiver_test.go, pkg/transfer/handle.go, pkg/transfer/store/s3_store.go
=> Dataset error improvements

cmd/job_run.go
This pull request let us complete the getting started guide: now we can use 
```
nerd job run --input=flights:/input --output=/output:co2-result --name=output-co2-calc nerdalize/co2-calculator 30
```
It will create a dataset `co2-result` if it doesn't exist
=> Create dataset if output ds doesn't exist, and change option order around

cmd/errors.go
=> Add link to status page to errors returned when cluster down

cmd/cmd.go, cmd/job_run.go, spec.json
Fixes #353 and partially fixes #354
=> Remove debug option from new commands

cmd/dataset_delete.go, cmd/job_delete.go
This allows people to run:
This answers partially to the issue #314
=> Add --all option to `nerd dataset delete` and `nerd job delete`

pkg/transfer/archiver/tar_archiver.go
=> Return proper err if upload target is not a dir

pkg/transfer/archiver/tar_archiver.go
=> Check target dir is empty before starting dl

svc/kube_fetch_job_logs.go
=> command now returns output from first pod that has any

cmd/errors.go, cmd/job_run.go
Fixes #359
Could be optimized (O(n^2))
=> Check if dataset is gonna be overwritten

svc/kube_list_jobs.go
Closes #355 
Before we were listing the datasets and then mapping the jobs and the datasets together. As the datasets contain a list of jobs that used them, if someone would name a job as a deleted job, this person would see in the job listing many datasets even if this job isn't using any dataset.
Now we use the job's specs: in the flex volume options we can find the `input/dataset` and `output/dataset`. This also removes one step, we don't have to list all the datasets to get a proper list of jobs.
=> Use flexvolume information to populate job listing

command/login.go, command/project_set.go, nerd/conf/conf.go, pkg/populator/oidc.go, pkg/populator/populator.go
Fixes #377 (partly) . It uses some default values proper to the staging environment, but it would also be cool to be able to configure each value through env var or a file.
=> Use env variable to switch between prod and staging environment

cmd/opts.go, command/login.go, command/project_set.go, spec.json
=> Update option to be kubeconfig instead of kube-config

README.md
=> cleaned up readme, added build instructions

cmd/flex/main.go, svc/kube_list_quotas.go
=> Allow flexvolume configuration via quota labels

cmd/job_run.go, svc/kube_create_secret.go
=> Extract tag from image to avoid secret validation error

cmd/flex/main.go
These were the causes of pods being stacked while waiting for unmount to happen.
If this is merged, then the immediate next steps are:
1. Redeploy flexvolume
2. Run smoketest to validate functionality
=> Change empty output directory and deleted dataset to be non-fatal errors

cmd/flex/dataset-dev.yml, cmd/flex/dataset.yml, cmd/flex/main.go, glide.lock
This aims to solve the problems we had with unmounts and has been tested three times with the smoketest so far. In case issues still happen, then we now also have more debugging information. It still requires some code restructuring and cleanup.
=> Attempt to fix flexvolume problems and add more debugging

cmd/cluster_list.go, cmd/cluster_use.go, cmd/errors.go, spec.json
=> Show short name if cluster name is empty

cmd/cluster_list.go, cmd/job_list.go
=> Update cluster and job list

cmd/dataset.go, cmd/dataset_delete.go, cmd/dataset_download.go, cmd/dataset_list.go, cmd/job.go, cmd/job_delete.go, cmd/job_list.go, cmd/job_logs.go, cmd/job_run.go, spec.json
=> Shorten dataset and job synopsis, extend their description

cmd/cluster_list.go, cmd/cluster_use.go, cmd/errors.go, cmd/login.go, nerd/client/auth/v1/client.go, svc/kube_nerd_compliant.go
=> Add timeout and feedback during login
